### ISSUE TITLE
Globus transfer task processing broken in devel branch

### ISSUE THREAD

**Issue by dvstans** [ORNL/DataFed#869]
With the addition of the "globus collection path" config option, the handling of data paths is inconsistent between transfer processing in the core (DB task api and TaskWorker) and the repo server API regarding the expected paths of data stored in the repository. In the case of transfer in the core, it is expected that the repo path (as configured for the datafed repo) + the data location path (on alloc edge) is the complete full path as needed to request a transfer via the globus api. However, in the repo server itself, paths are prepended with the globus collection path - this will (should?) cause the repose get size request to fail since the computed path is invalid.

This may also cause the path create/delete requests in the repo server to fail as well. Need to fully investigate the impact/usage of the globus collection path to ensure all paths are consistent.

**Comment by JoshuaSBrown** [comment]
This is no longer an issue. There are three places where the posix path has to be correctly configured, and is a significant source of error, the repo server the globus authz library and the in the metadata services when the container is registered. Moving to containers and automating the set up process has simplified this. Closing because devel is no longer broken.
